[tool.poetry]
name = "aarre laakso"
version = "0.0.1"
description = "Personal website for Aarre Laakso"
authors = ["Aarre Laakso <aarre.laakso@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
